#!/usr/bin/env node
const program = require('commander')
const packager = require('./package.json')
const server = require('./src/bin/server')
const migrate = require('./src/bin/migrate')
const replicate = require('./src/bin/replicate')

program
  .version(packager.version, '-v, --version')

program
  .command('migrate <version/all>')
  .action((version) => {
    migrate.init(`${__dirname}/migrations`)
    migrate.to(version)
  })

program
  .command('start')
  .action(() => {
    server.init()
  })

program
  .command('replicate')
  .action(() => {
    replicate.init()
  })

program.parse(process.argv)