#!/usr/bin/env node
const program = require('commander')
const packager = require('./package.json')
const server = require('./src/lib/server')
const migrate = require('./src/lib/migrate')

program
  .version(packager.version, '-v, --version')

program
  .command('migrate <version/all>')
  .action((version) => {
    migrate.init(`${__dirname}/migrations`)
    migrate.to(version)
  })

program
  .command('start')
  .action(() => {
    server.init()
  })

program.parse(process.argv)