DROP TABLE IF EXISTS keywords;
DROP TABLE IF EXISTS npm;
DROP TABLE IF EXISTS dependencies;
DROP TABLE IF EXISTS contributors;
DROP TABLE IF EXISTS humans;
DROP TABLE IF EXISTS packages;
DROP EXTENSION IF EXISTS "uuid-ossp";