CREATE TABLE IF NOT EXISTS packages (
	uuid UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	id VARCHAR(128),
	rev VARCHAR(128),
	name VARCHAR(128),
	description TEXT,
	author UUID,
	distributionLatest VARCHAR(32),
	latestName VARCHAR(128),
	latestDescription VARCHAR(128),
	latestVersion VARCHAR(16),
	latestAuthor UUID,
	latestDistShasum VARCHAR(64),
	latestDistTarball VARCHAR(256),
	latestDeprecated VARCHAR(256),
	timeModified TIMESTAMP WITH TIME ZONE,
	timeCreated TIMESTAMP WITH TIME ZONE,
	timeLatest TIMESTAMP WITH TIME ZONE,
	repoType VARCHAR(16),
	repoURL VARCHAR(256),
	repoGithubOrg VARCHAR(64),
	repoGithubRepo VARCHAR(64),
	readme TEXT,
	readmeFileName VARCHAR(256),
	homepage VARCHAR(64),
	bugs VARCHAR(128),
	licence VARCHAR(16),
	created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
	updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);