CREATE TABLE IF NOT EXISTS downloads (
  uuid UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR,
  startTime TIMESTAMP WITH TIME ZONE,
  endTime TIMESTAMP WITH TIME ZONE,
  downloads BIGINT,
  created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);