CREATE TABLE IF NOT EXISTS humans (
	uuid UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	email VARCHAR(64),
	name VARCHAR(64),
	url VARCHAR(64),
	created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
	updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);