CREATE TABLE IF NOT EXISTS github (
  uuid UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR,
  avatarURL VARCHAR,
  description VARCHAR,
  createdAt TIMESTAMP WITH TIME ZONE,
  updatedAt TIMESTAMP WITH TIME ZONE,
  pushedAt TIMESTAMP WITH TIME ZONE,
  homepage VARCHAR,
  size BIGINT,
  stars BIGINT,
  subscribers BIGINT,
  forks BIGINT,
  openIssueCount BIGINT,
  language VARCHAR,
  licence VARCHAR,
  archived BOOL,
  disabled BOOL,
  created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);